version: '3.4'

services:
  db:
    image: "${REGISTRY_NAME}postgres:10.1-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - "internal"
    env_file:
      - ./.env
    restart: always
  web:
    build: .
    working_dir: /Yearbook
    image: "${REGISTRY_NAME}devclubiitd/yearbook:0.1"
    command: ./docker_entry_point.sh
    volumes:
      - yearbook_media:/Yearbook/media/myapp/static/myapp
    ports:
      - 7000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always 
    networks:
      - "reverseproxy"
      - "internal"
    env_file:
      - ./.env
    environment:
      - PORT=7000
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - POSTGRES_HOST_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    depends_on:
      - db
    links:
      - db:db

volumes:
  postgres_data:
  yearbook_media:

networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal:
